date_format: '%Y-%m-%d %H:%M:%S'
format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console: true
  file: logs/debug_agent.log
  rotation:
    backup_count: 5
    enabled: true
    max_bytes: 10485760
level: INFO
settings:
  module_levels:
    httpx: WARNING
    langchain: INFO
    matplotlib: WARNING
    src.realtime: DEBUG
    urllib3: WARNING
