version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: data/logs/debug_agent/debug_agent.log
    mode: a
    encoding: utf8

loggers:
  '':  # root logger
    handlers: [console, file]
    level: INFO
    propagate: true

  httpx:
    level: WARNING
    handlers: [console, file]
    propagate: false

  matplotlib:
    level: WARNING
    handlers: [console, file]
    propagate: false

  urllib3:
    level: WARNING
    handlers: [console, file]
    propagate: false

  langchain:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.realtime:
    level: DEBUG
    handlers: [console, file]
    propagate: false
